### PR TITLE
Make readme examples async

### PR DESCRIPTION
**Pull request by danfinlay**
This makes copy-pasting metamask compatible.

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks! However, the readme is generated using the `documentation` command from the JS doccomments - so those need to be updated instead.

**Comment by danfinlay** [comment]
Ahh!

**Comment by danfinlay** [comment]
Sorry, could you point me to where the `doccomments` are?  I really think people need async examples.

**Comment by Arachnid** [comment]
Sorry for the delay responding. You can see them here, for instance: https://github.com/Arachnid/ensjs/blob/master/index.js#L365

This might be obsolete, though, as I've since migrated the library to use promises instead.

**Pull request closed without merging**
